easy_admin:
    site_name: 'Event Configuration'
    entities:
        Event:
            class: App\Entity\Event\Event
            form:
                fields: 
                    - name
                    - slug
                    - { property: 'startDate', type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType', type_options: { required: true, date_widget: single_text, time_widget: single_text }  }
                    - { property: 'endDate', type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType', type_options: { required: true, date_widget: single_text, time_widget: single_text }  }
                    - venues
                    - { property: 'messages', type_options: { by_reference: false} }
                    - style
                    - { property: 'screen_size', type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', type_options: { required: true, choices: { 'Normal': 'normal', 'Small': 'small' } } }
                    - { property: 'locale', type: 'Symfony\Component\Form\Extension\Core\Type\LanguageType', type_options: { required: true, choices: { 'English': 'en', 'Français': 'fr' }, choice_loader: null } }
            list:
                actions:
                    - { name: 'reload_clients', icon: 'refresh', type: 'route' }
        Message:
            class: App\Entity\Event\Message
            form:
                fields:
                    - message_line_1
                    - message_line_2
                    - message_line_3
                    - { property: 'startDate', type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType', type_options: { required: false, date_widget: single_text, time_widget: single_text }  }
                    - { property: 'endDate', type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType', type_options: { required: false, date_widget: single_text, time_widget: single_text }  }
                    - event
        Style:
            class: App\Entity\Event\Style
            form:
                fields:
                    - name
                    - { property: 'header_background_color', type: 'Symfony\Component\Form\Extension\Core\Type\ColorType' }
                    - { property: 'header_text_color', type: 'Symfony\Component\Form\Extension\Core\Type\ColorType' }
                    - { property: 'link_color', type: 'Symfony\Component\Form\Extension\Core\Type\ColorType' }
                    - { property: 'major_info_color', type: 'Symfony\Component\Form\Extension\Core\Type\ColorType' }
                    - { property: 'untappd_logo_style', type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', type_options: { required: true, choices: { 'Black': 'black', 'White': 'white' } } }