easy_admin:
    site_name: 'Event Configuration'
    entities:
        Event:
            class: App\Entity\Event\Event
            form:
                fields: 
                    - name
                    - slug
                    - { property: 'startDate', type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType', type_options: { required: true, date_widget: single_text, time_widget: single_text }  }
                    - { property: 'endDate', type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType', type_options: { required: true, date_widget: single_text, time_widget: single_text }  }
                    - sessions
                    - venues
                    - { property: 'messages', type_options: { by_reference: false} }
                    - style
                    - { property: 'screen_size', type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', type_options: { required: true, choices: { 'Normal': 'normal', 'Small': 'small' } } }
                    - { property: 'locale', type: 'Symfony\Component\Form\Extension\Core\Type\LanguageType', type_options: { required: true, choices: { 'English': 'en', 'Français': 'fr' }, choice_loader: null } }
                    - moderated
                    - has_taplist
            list:
                actions:
                    - { name: 'reload_clients', icon: 'refresh', type: 'route' }
        Session:
            class: App\Entity\Event\Session
            form:
                fields:
                    - name
                    - event
                    - { property: 'startDate', type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType', type_options: { required: false, date_widget: single_text, time_widget: single_text }  }
                    - { property: 'endDate', type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType', type_options: { required: false, date_widget: single_text, time_widget: single_text }  }
                    - { property: 'color', type: 'Symfony\Component\Form\Extension\Core\Type\ColorType' }
        Message:
            class: App\Entity\Event\Message
            form:
                fields:
                    - message_line_1
                    - message_line_2
                    - message_line_3
                    - { property: 'startDate', type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType', type_options: { required: false, date_widget: single_text, time_widget: single_text }  }
                    - { property: 'endDate', type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType', type_options: { required: false, date_widget: single_text, time_widget: single_text }  }
                    - do_not_broadcast
                    - event
        Style:
            class: App\Entity\Event\Style
            form:
                fields:
                    - name
                    - { property: 'header_background_color', type: 'Symfony\Component\Form\Extension\Core\Type\ColorType' }
                    - { property: 'header_text_color', type: 'Symfony\Component\Form\Extension\Core\Type\ColorType' }
                    - { property: 'link_color', type: 'Symfony\Component\Form\Extension\Core\Type\ColorType' }
                    - { property: 'major_info_color', type: 'Symfony\Component\Form\Extension\Core\Type\ColorType' }
                    - { property: 'untappd_logo_style', type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', type_options: { required: true, choices: { 'Black': 'black', 'White': 'white' } } }
        Publisher:
            class: App\Entity\Event\Publisher
            form:
                fields:
                    - name
                    - { property: 'access_key', type: 'Symfony\Component\Form\Extension\Core\Type\TextType', type_options: { disabled: true } }
                    - { property : 'email', type: 'Symfony\Component\Form\Extension\Core\Type\EmailType' }
                    - notified
                    - { property: 'language', type: 'Symfony\Component\Form\Extension\Core\Type\LanguageType', type_options: { required: true, choices: { 'English': 'en', 'Français': 'fr' }, choice_loader: null } }
                    - { property : 'last_publication_date', type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType', type_options: { date_widget: single_text, time_widget: single_text } }
                    - remaining_messages
                    - location
                    - event
        Beer:
            class: App\Entity\Beer\Beer
            form:
                fields:
                    - name
                    - brewery
                    - style
                    - abv
                    - ibu
                    - label
                    - description
                    - slug
                    - rating_count
                    - parent
                    - extra_info
                    